import type { Metadata } from 'next';
import { Inter, Open_Sans } from 'next/font/google';
import SessionProvider from '@/providers/SessionProvider';
import './globals.css';
import { cn } from '@/lib/utils';
import { getServerSession } from 'next-auth';

// const inter = Inter({ subsets: ['latin'] });
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={cn('bg-gray-3 text-white', openSans.className)}>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
